--[[
    // SexFuscate | Version 1.0.3 \\
    [+] Added support for the number 1 and dynamic function encryption in Algo gen
    [+] Added dynamic structure generation for the encryptions
    [+] Added XOR encryption with key 'testkey' [ Expect an upd soon ]
    [-] Removed short outputs
    [+] Fixed the breaker to support methodcalls
    [+] Fixed operators patterns for the lexer
    [+] Added new keywords in the lexer
    [+] Enhanced the obfuscation method
--]]
