return(function(...) 
    do 
        local sex='This file was sexified by SexFuscator | 1.69.0' 
    end
    do 
        local _SEXlI111I11llll11I = print;
        local _SEX11l11IIl1lIIl1l=math.floor((16 * 10^4 - 75 * 10^3 + 41 * 10^2 - 103 * 10 + 82) / (16 * 10^3 - 75 * 10^2 + 41 * 10 - 103))
        print("Robus", _SEX11l11IIl1lIIl1l)
        function _SEXlII11I1IllIll1l(_SEXII1I1I11I1Il1I1)
            _SEX11l11IIl1lIIl1l = _SEX11l11IIl1lIIl1l + _SEXII1I1I11I1Il1I1
            return "\100\111\110\101" 
        end 
        _SEXlI111I11llll11I("\65\100\100\105\110\103\32\116\104\101\32\117\115\101\114\32\53\32\114\111\98\117\120")
        local xy = _SEXlII11I1IllIll1l(math.floor((46 * 5^4 - 12 * 5^3 + 53 * 5^2 - 92 * 5 + 23) / (46 * 5^3 - 12 * 5^2 + 53 * 5 - 92)))
        _SEXlI111I11llll11I(xy)
        _SEXlI111I11llll11I("\84\104\101\32\117\115\101\114\32\104\97\115\32\58",robux,"\114\111\98\117\120") 
    end 
    do 
    end 
end)()

-- What was happening ?
-- When running more than 1 time the same function, it redefined another variable, which broke the ENV
-- Fixed : Yes
-- Date : 14/07/2024